import type { Metadata } from 'next';
import { getPageMetadata } from '../lib/seo';

interface PolicyGroup {
  heading?: string;
  paragraphs: string[];
  list?: string[];
}

interface PolicySection {
  title: string;
  groups: PolicyGroup[];
}

const sections: PolicySection[] = [
  {
    title: 'Interpretation and Definitions',
    groups: [
      {
        heading: 'Interpretation',
        paragraphs: [
          'The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
        ],
      },
      {
        heading: 'Definitions',
        paragraphs: ['For the purposes of this Privacy Policy:'],
        list: [
          'Account means a unique account created for You to access our Service or parts of our Service.',
          'Affiliate means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
          'Company refers to Pearl Remote.',
          'Cookies are small files that are placed on Your computer, mobile device or any other device by a website.',
          'Country refers to: Philippines.',
          'Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
          'Personal Data or Personal Information means any information that relates to an identified or identifiable individual.',
          'Service refers to the Website.',
          'Service Provider means any natural or legal person who processes the data on behalf of the Company.',
          'Usage Data refers to data collected automatically, either generated by use of the Service or from the Service infrastructure itself.',
          'Website refers to Pearl Remote, accessible from http://pearlremote.com/.',
          'You means the individual accessing or using the Service, or the company or legal entity on behalf of which such individual is accessing or using the Service.',
        ],
      },
    ],
  },
  {
    title: 'Collecting and Using Your Personal Data',
    groups: [
      {
        heading: 'Types of Data Collected',
        paragraphs: [
          'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You, including email address, first name, and last name.',
          'Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device IP address, browser type, browser version, pages visited, visit time and date, time spent on pages, unique device identifiers, and other diagnostic data.',
          'When You access the Service by or through a mobile device, We may collect certain information automatically, including the type of mobile device, mobile device unique ID, IP address, operating system, browser type, unique device identifiers, and other diagnostic data.',
        ],
      },
      {
        heading: 'Tracking Technologies and Cookies',
        paragraphs: [
          'We use Cookies and similar tracking technologies to track activity on Our Service and store certain information. Tracking technologies We use may include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.',
          'You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.',
          'Where required by law, We use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool, if available, or through Your browser or device settings.',
        ],
        list: [
          'Necessary / Essential Cookies: Session Cookies administered by Us and essential to provide services available through the Website.',
          'Cookies Policy / Notice Acceptance Cookies: Persistent Cookies administered by Us to identify whether users have accepted cookie use on the Website.',
          'Functionality Cookies: Persistent Cookies administered by Us to remember choices You make when You use the Website.',
        ],
      },
      {
        heading: 'Use of Your Personal Data',
        paragraphs: [
          'The Company may use Personal Data for the following purposes:',
        ],
        list: [
          'To provide and maintain Our Service, including monitoring usage of Our Service.',
          'To manage Your Account and provide access to Service functionality.',
          'For the performance of a contract for products, items, or services You have purchased or requested.',
          'To contact You by email, telephone, SMS, or other equivalent forms of electronic communication.',
          'To provide You with news, special offers, and general information about goods, services, and events unless You have opted out.',
          'To manage Your requests.',
          'For business transfers.',
          'For other purposes such as data analysis, identifying usage trends, evaluating promotional campaigns, and improving Our Service and experience.',
        ],
      },
      {
        heading: 'Sharing Your Personal Data',
        paragraphs: [
          'We may share Your Personal Data in the following situations:',
        ],
        list: [
          'With Service Providers to monitor and analyze use of Our Service or to contact You.',
          'For business transfers in connection with a merger, sale of Company assets, financing, or acquisition.',
          'With Affiliates, which must honor this Privacy Policy.',
          'With business partners to offer You certain products, services, or promotions.',
          'With other users if Our Service offers public areas and You share Personal Data there.',
          'With Your consent for any other purpose.',
        ],
      },
    ],
  },
  {
    title: 'Retention of Your Personal Data',
    groups: [
      {
        heading: 'Retention Periods',
        paragraphs: [
          'The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to comply with legal obligations, resolve disputes, and enforce Our legal agreements and policies.',
          'Where possible, We apply shorter retention periods or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods and We may delete or anonymize data sooner.',
        ],
        list: [
          'User Accounts: retained for the duration of Your account relationship plus up to 24 months after account closure.',
          'Support tickets and correspondence: up to 24 months from ticket closure.',
          'Chat transcripts: up to 24 months for quality assurance and staff training purposes.',
          'Website analytics data: up to 24 months from collection.',
          'Server logs: up to 24 months for security monitoring and troubleshooting.',
        ],
      },
      {
        heading: 'Longer Retention and Deletion',
        paragraphs: [
          'We may retain Personal Data beyond the periods stated above when required by legal obligations, legal claims, Your explicit request, or technical limitations such as backup systems scheduled for routine deletion.',
          'When retention periods expire, We securely delete or anonymize Personal Data. Residual copies may remain in encrypted backups for a limited period and are not restored except where necessary for security, disaster recovery, or legal compliance.',
        ],
      },
    ],
  },
  {
    title: 'Transfer of Your Personal Data',
    groups: [
      {
        paragraphs: [
          'Your information, including Personal Data, is processed at the Company operating offices and in any other places where the parties involved in processing are located. This means information may be transferred to and maintained on computers outside Your state, province, country, or other governmental jurisdiction.',
          'Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate.',
        ],
      },
    ],
  },
  {
    title: 'Delete Your Personal Data',
    groups: [
      {
        paragraphs: [
          'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.',
          'You may update, amend, or delete Your information at any time by signing in to Your Account, if You have one, and visiting account settings. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.',
          'Please note that We may need to retain certain information when We have a legal obligation or lawful basis to do so.',
        ],
      },
    ],
  },
  {
    title: 'Disclosure of Your Personal Data',
    groups: [
      {
        heading: 'Business Transactions',
        paragraphs: [
          'If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.',
        ],
      },
      {
        heading: 'Law Enforcement and Legal Requirements',
        paragraphs: [
          'Under certain circumstances, the Company may be required to disclose Your Personal Data if required by law or in response to valid requests by public authorities.',
          'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing, protect personal safety, or protect against legal liability.',
        ],
      },
    ],
  },
  {
    title: 'Security of Your Personal Data',
    groups: [
      {
        paragraphs: [
          'The security of Your Personal Data is important to Us, but no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.',
        ],
      },
    ],
  },
  {
    title: "Children's Privacy",
    groups: [
      {
        paragraphs: [
          'Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.',
          'If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.',
        ],
      },
    ],
  },
  {
    title: 'Links to Other Websites',
    groups: [
      {
        paragraphs: [
          'Our Service may contain links to other websites that are not operated by Us. If You click a third-party link, You will be directed to that third party site. We strongly advise You to review the Privacy Policy of every site You visit.',
          'We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.',
        ],
      },
    ],
  },
  {
    title: 'Changes to this Privacy Policy',
    groups: [
      {
        paragraphs: [
          'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.',
          'We will update the Last updated date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.',
          'Changes to this Privacy Policy are effective when they are posted on this page.',
        ],
      },
    ],
  },
  {
    title: 'Contact Us',
    groups: [
      {
        paragraphs: [
          'If You have any questions about this Privacy Policy, You can contact Us by email: dacs00015@gmail.com.',
          'Generated using Privacy Policies Generator.',
        ],
      },
    ],
  },
];

export const metadata: Metadata = getPageMetadata(
  {
    title: 'Privacy Policy | Pearl Remote',
    description:
      'Read Pearl Remote privacy policy, including how personal data, usage data, and cookies are collected, used, retained, and protected.',
  },
  '/privacy-policy'
);

export default function PrivacyPolicyPage() {
  return (
    <main className='bg-page-surface'>
      <section className='container px-6 py-16 lg:py-24'>
        <div>
          <p className='text-primary text-sm font-semibold tracking-[0.16em] uppercase'>
            Pearl Remote
          </p>
          <h1 className='text-heading font-display mt-4 text-4xl leading-tight font-bold md:text-5xl'>
            Privacy Policy
          </h1>
          <p className='mt-4 text-sm font-semibold'>
            Last updated: June 04, 2026
          </p>
          <p className='mt-8 text-lg leading-8'>
            This Privacy Policy describes Our policies and procedures on the
            collection, use, and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p className='mt-4 text-lg leading-8'>
            We use Your Personal Data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </div>
      </section>

      <section className='container px-6 pb-20 lg:pb-28'>
        <div className='bg-card-surface rounded-3xl px-6 py-8 shadow-sm md:px-10 md:py-12'>
          <div className='space-y-12'>
            {sections.map((section) => (
              <article key={section.title} className='space-y-6'>
                <h2 className='text-heading font-display text-2xl font-bold'>
                  {section.title}
                </h2>
                <div className='space-y-6'>
                  {section.groups.map((group, index) => (
                    <div
                      key={`${section.title}-${group.heading ?? index}`}
                      className='space-y-4'
                    >
                      {group.heading ? (
                        <h3 className='text-heading text-lg font-bold'>
                          {group.heading}
                        </h3>
                      ) : null}
                      {group.paragraphs.map((paragraph) => (
                        <p key={paragraph} className='leading-7'>
                          {paragraph}
                        </p>
                      ))}
                      {group.list ? (
                        <ul className='list-disc space-y-3 pl-6 leading-7'>
                          {group.list.map((item) => (
                            <li key={item}>{item}</li>
                          ))}
                        </ul>
                      ) : null}
                    </div>
                  ))}
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>
    </main>
  );
}
